Студент Жилкин Федор, 344
# Домашняя работа 3: "Решение частичной проблемы собственных значений."
**Задания:**

1. Степенной метод 
2. Метод скалярных произведений

In [1]:
import numpy as np

In [9]:
A = np.array([[1., 2., 1.], [0., 5., 1.], [6., 4, -1.]])

## Степенной метод 

In [42]:
def power_method(A, i):
    
    # Рандомный вектор
    b = np.random.rand(A.shape[1])

    for _ in range(i):
        b_new = np.dot(A, b)
        b_new_norm = np.linalg.norm(b_new)
        b = b_new / b_new_norm

    return b

In [43]:
power_method(A, 100000)

array([0.38101118, 0.62851092, 0.67808886])

In [44]:
np.linalg.eig(A)

(array([-2.71489544,  1.63601384,  6.0788816 ]),
 array([[ 0.19399208, -0.52143364, -0.38101118],
        [ 0.1261021 ,  0.24313957, -0.62851092],
        [-0.9728645 , -0.81791815, -0.67808886]]))